### ISSUE TITLE
Hyperparameters for expert trajectories

### ISSUE THREAD

**Issue by sff1019** [SaminYeasar/Off_Policy_Adversarial_Inverse_Reinforcement_Learning#2]
Thank you for your amazing work!

I am also trying to use off-policy in my IRL project, however, I am having a hard time creating expert trajectories.
I found that you have achieved good expert trajectories in your work, and I was curious if it was possible for you to share the expert trajectories for your experiments.
Especially, it would be great if you can include the data for PointMazeLeft.

**Comment by SaminYeasar** [comment]
Hi, the link for the expert trajectories is shared in the repository (link provided in the readme file). Please let me know if the link does not work

**Comment by sff1019** [comment]
@SaminYeasar I saw the link, but these does not include the hyperparameters for the training. Will it be possible for you to share these as well?
