### ISSUE TITLE
Hyperparameters for expert trajectories

### ISSUE THREAD

**Issue by sff1019** [SaminYeasar/Off_Policy_Adversarial_Inverse_Reinforcement_Learning#3]
The previous issue #2 seems to be closed, hence opening a new one.
I saw the link for the expert trajectories, but these does not include the hyperparameters or training script. Will it be possible for you to share these as well?
E.g. lr, noise, batch_size, etc.

Thank you,

**Comment by SaminYeasar** [comment]
Hi, this implementation of soft-actor-critic (https://github.com/denisyarats/pytorch_sac) (with default hyper-parameter) should work fine.

**Comment by sff1019** [comment]
Yes, it does seem work! Thank you!
